# Generated by Django 5.1.7 on 2025-04-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0002_alter_category_options_alter_subtask_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('marketing', 'Marketing'), ('development', 'Development'), ('sales', 'Sales')], default='Marketing', max_length=20),
        ),
    ]
