# Generated by Django 5.1.7 on 2025-04-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0003_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='day_of_week',
            field=models.CharField(default='Monday', max_length=20),
        ),
    ]
