# Generated by Django 5.1.7 on 2025-05-19 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0006_subtask_owner_task_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='task',
            name='owner',
        ),
    ]
